#logo: /assets/img/foto_perfil_3.png
#title: Syã Fonseca
#description: Data insights drive better decisions.
#show_downloads: false  # precisa ser tudo minúsculo: "false"
#google_analytics:      # se não for usar, pode remover ou deixar em branco

theme: jekyll-theme-minimal

# Inclui customizações no <head>
include:
  - _includes/head-custom.html

# Informações de contato e autor
linkedin: https://www.linkedin.com/in/syafonseca/
github: https://github.com/fonsecadados
email: syafonseca@gmail.com
author: Syã Fonseca
lang: pt-BR

# Configurações de URL
url: "https://fonsecadados.github.io"
baseurl: ""  # Se for publicado direto no GitHub Pages principal. Mude para "/nome-do-repo" se necessário

# Melhora as URLs (sem .html no final)
permalink: pretty
