title: Syã Fonseca
logo: /assets/img/foto_perfil_2.png
description:  Data insights drive better decisions.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
social_links:
  linkedin: https://www.linkedin.com/in/syafonseca/
  github: https://github.com/fonsecadados
  email: syafonseca@gmail.com
author: Syã Fonseca
lang: pt-BR
url: "https://fonsecadados.github.io"
baseurl: ""  # Substitua se estiver em um subdiretório (ex: "/portfolio")
permalink: pretty