title: Minimal theme
logo: /assets/img/foto_perfil_3.png
description: Minimal is a theme for GitHub Pages.
# show_downloads: False
google_analytics:
theme: jekyll-theme-minimal

include:
  - _includes/header.html